{% set standard_keys = ['secret', 'hypothesis_api_url', 'hypothesis_api_publisher', 'ttl']  %}

parameters:

    {% for name in standard_keys %}
    {% set value = pillar.annotations.get(name, 'null') %}
    {% if value == '' %}
    {{ name }}: ''
    {% elif value is not none %}
    {{ name }}: {{ value }}
    {% else %}
    {{ name }}: null
    {% endif %}
    {% endfor %}

    trusted_hosts: ['^(.+\.)?{{ pillar.elife.domain }}$', 'localhost', '^10\.[0-9]+\.[0-9]+\.[0-9]+$', '^172\.(16|17|18|19|2[0-9]|30|31)\.[0-9]+\.[0-9]+$', '^192.168\.[0-9]+\.[0-9]+$']
